import {
  Tenant,
  RestaurantUser,
  Transaction,
  PlanPricingTier,
  SystemServiceTelemetry,
  AlertNotification,
} from '../types';

/**
 * INITIAL DATABASE SEED DATA
 * Used EXCLUSIVELY by `seedSupabaseDatabaseIfEmpty()` to populate real rows
 * into the user's Supabase PostgreSQL database tables.
 * This is NEVER used as fallback or initial UI state.
 */

export const INITIAL_DATABASE_SEED_TENANTS: Tenant[] = [
  {
    id: 'TEN-8841',
    businessName: 'The Monal Hospitality Group Pvt Ltd',
    tradeName: 'The Monal Restaurant Islamabad',
    registrationNumber: 'PK-NTN-4829104-1',
    primaryContact: {
      name: 'Luqman Ali Afzal',
      email: 'luqman@themonal.com',
      phone: '+92 (51) 2898044',
      role: 'CEO & Founder',
    },
    planTier: 'Enterprise',
    mrr: 350000,
    status: 'Active',
    dateJoined: '2025-04-12',
    timezone: 'Asia/Karachi',
    locale: 'en-PK',
    currency: 'PKR',
    region: 'APAC',
    healthScore: 98,
    limits: {
      posTerminals: { current: 14, max: 20 },
      staffSeats: { current: 42, max: 60 },
      apiRateLimitPerMin: 1200,
      locationsCount: 3,
    },
    featureFlags: {
      posEnabled: true,
      kdsEnabled: true,
      qrOrderingEnabled: true,
      inventoryEnabled: true,
      apiAccessEnabled: true,
      multiLocationEnabled: true,
    },
    location: {
      address: 'Pir Sohawa Road, Margalla Hills',
      city: 'Islamabad',
      province: 'Federal Capital',
      postalCode: '44000',
      country: 'Pakistan',
      coordinates: { lat: 33.74318, lng: 73.06822 },
      landmark: 'Margalla Hilltop Flagship',
    },
    lastActive: '2026-03-11T08:30:00.000Z',
    openTicketsCount: 0,
  },
  {
    id: 'TEN-7102',
    businessName: 'Kolachi Seafood & BBQ Ltd',
    tradeName: 'Kolachi Restaurant Karachi',
    registrationNumber: 'PK-NTN-1940291-7',
    primaryContact: {
      name: 'Noman Noorani',
      email: 'noman@kolachi.pk',
      phone: '+92 (21) 111-111-001',
      role: 'Managing Partner',
    },
    planTier: 'Enterprise',
    mrr: 420000,
    status: 'Active',
    dateJoined: '2025-01-20',
    timezone: 'Asia/Karachi',
    locale: 'en-PK',
    currency: 'PKR',
    region: 'APAC',
    healthScore: 95,
    limits: {
      posTerminals: { current: 18, max: 25 },
      staffSeats: { current: 55, max: 70 },
      apiRateLimitPerMin: 1500,
      locationsCount: 2,
    },
    featureFlags: {
      posEnabled: true,
      kdsEnabled: true,
      qrOrderingEnabled: true,
      inventoryEnabled: true,
      apiAccessEnabled: true,
      multiLocationEnabled: true,
    },
    location: {
      address: 'Beach Avenue, Phase VIII, DHA Creek',
      city: 'Karachi',
      province: 'Sindh',
      postalCode: '75500',
      country: 'Pakistan',
      coordinates: { lat: 24.77612, lng: 67.06941 },
      landmark: 'Do Darya Coastal Waterfront',
    },
    lastActive: '2026-03-11T09:12:00.000Z',
    openTicketsCount: 1,
  },
  {
    id: 'TEN-6490',
    businessName: 'Saltn Pepper Food Services Pvt Ltd',
    tradeName: 'Salt’n Pepper Village Lahore',
    registrationNumber: 'PK-NTN-7362019-3',
    primaryContact: {
      name: 'Mahmood Akbar',
      email: 'mahmood@saltnpepper.com.pk',
      phone: '+92 (42) 35850900',
      role: 'Executive Director',
    },
    planTier: 'Enterprise',
    mrr: 290000,
    status: 'Active',
    dateJoined: '2025-06-18',
    timezone: 'Asia/Karachi',
    locale: 'en-PK',
    currency: 'PKR',
    region: 'APAC',
    healthScore: 92,
    limits: {
      posTerminals: { current: 12, max: 15 },
      staffSeats: { current: 36, max: 45 },
      apiRateLimitPerMin: 1000,
      locationsCount: 4,
    },
    featureFlags: {
      posEnabled: true,
      kdsEnabled: true,
      qrOrderingEnabled: true,
      inventoryEnabled: true,
      apiAccessEnabled: false,
      multiLocationEnabled: true,
    },
    location: {
      address: '103-B/II, MM Alam Road, Gulberg III',
      city: 'Lahore',
      province: 'Punjab',
      postalCode: '54660',
      country: 'Pakistan',
      coordinates: { lat: 31.51268, lng: 74.35415 },
      landmark: 'Gulberg Food Hub',
    },
    lastActive: '2026-03-11T08:50:00.000Z',
    openTicketsCount: 0,
  },
  {
    id: 'TEN-5211',
    businessName: 'Howdy Gourmet Foods Ltd',
    tradeName: 'Howdy Steak & Burgers Lahore',
    registrationNumber: 'PK-NTN-9024185-2',
    primaryContact: {
      name: 'Raza Farooq',
      email: 'raza@howdy.pk',
      phone: '+92 (42) 111-469-391',
      role: 'Operations Head',
    },
    planTier: 'Professional',
    mrr: 145000,
    status: 'Active',
    dateJoined: '2025-09-05',
    timezone: 'Asia/Karachi',
    locale: 'en-PK',
    currency: 'PKR',
    region: 'APAC',
    healthScore: 89,
    limits: {
      posTerminals: { current: 7, max: 10 },
      staffSeats: { current: 22, max: 30 },
      apiRateLimitPerMin: 600,
      locationsCount: 3,
    },
    featureFlags: {
      posEnabled: true,
      kdsEnabled: true,
      qrOrderingEnabled: true,
      inventoryEnabled: false,
      apiAccessEnabled: false,
      multiLocationEnabled: true,
    },
    location: {
      address: 'Sector Z, Phase 3, DHA',
      city: 'Lahore',
      province: 'Punjab',
      postalCode: '54792',
      country: 'Pakistan',
      coordinates: { lat: 31.47211, lng: 74.3812 },
      landmark: 'DHA Z-Block Outpost',
    },
    lastActive: '2026-03-10T22:15:00.000Z',
    openTicketsCount: 0,
  },
  {
    id: 'TEN-4190',
    businessName: 'Charsi Tikka Enterprises',
    tradeName: 'Khyber Shinwari Peshawar',
    registrationNumber: 'PK-NTN-3128945-8',
    primaryContact: {
      name: 'Nisar Khan Charsi',
      email: 'nisar@shinwaritikka.pk',
      phone: '+92 (91) 2568912',
      role: 'Proprietor',
    },
    planTier: 'Professional',
    mrr: 120000,
    status: 'Trial',
    dateJoined: '2026-02-14',
    trialEndsAt: '2026-03-24',
    timezone: 'Asia/Karachi',
    locale: 'ur-PK',
    currency: 'PKR',
    region: 'APAC',
    healthScore: 84,
    limits: {
      posTerminals: { current: 5, max: 8 },
      staffSeats: { current: 15, max: 20 },
      apiRateLimitPerMin: 500,
      locationsCount: 1,
    },
    featureFlags: {
      posEnabled: true,
      kdsEnabled: true,
      qrOrderingEnabled: true,
      inventoryEnabled: false,
      apiAccessEnabled: false,
      multiLocationEnabled: false,
    },
    location: {
      address: 'Namak Mandi, Heritage Bazaar',
      city: 'Peshawar',
      province: 'Khyber Pakhtunkhwa',
      postalCode: '25000',
      country: 'Pakistan',
      coordinates: { lat: 34.00845, lng: 71.57219 },
      landmark: 'Namak Mandi Traditional Karahi',
    },
    lastActive: '2026-03-11T07:45:00.000Z',
    openTicketsCount: 0,
  },
];

export const INITIAL_DATABASE_SEED_USERS: RestaurantUser[] = [
  {
    id: 'USR-PK-101',
    tenantId: 'TEN-8841',
    tenantName: 'The Monal Restaurant Islamabad',
    fullName: 'Hamza Tariq',
    email: 'hamza.tariq@themonal.com',
    role: 'manager',
    status: 'active',
    branch: 'Margalla Hilltop Flagship',
    phone: '+92 300 8521094',
    lastLogin: '2026-03-10 18:42 PKT',
    createdAt: '2025-04-14',
    permissions: {
      pos: true,
      kds: true,
      inventory: true,
      reports: true,
      staffManagement: true,
      billing: false,
    },
  },
  {
    id: 'USR-PK-102',
    tenantId: 'TEN-8841',
    tenantName: 'The Monal Restaurant Islamabad',
    fullName: 'Chef Aslam Pervaiz',
    email: 'chef.aslam@themonal.com',
    role: 'chef',
    status: 'active',
    branch: 'Margalla Hilltop Flagship',
    phone: '+92 321 4492102',
    lastLogin: '2026-03-10 19:15 PKT',
    createdAt: '2025-04-15',
    permissions: {
      pos: false,
      kds: true,
      inventory: true,
      reports: false,
      staffManagement: false,
      billing: false,
    },
  },
  {
    id: 'USR-PK-201',
    tenantId: 'TEN-7102',
    tenantName: 'Kolachi Restaurant Karachi',
    fullName: 'Sara Nadeem',
    email: 'sara.operations@kolachi.pk',
    role: 'owner',
    status: 'active',
    branch: 'Do Darya Coastal Waterfront',
    phone: '+92 333 2189045',
    lastLogin: '2026-03-10 20:05 PKT',
    createdAt: '2025-01-22',
    permissions: {
      pos: true,
      kds: true,
      inventory: true,
      reports: true,
      staffManagement: true,
      billing: true,
    },
  },
  {
    id: 'USR-PK-301',
    tenantId: 'TEN-6490',
    tenantName: 'Salt’n Pepper Village Lahore',
    fullName: 'Usman Ghani',
    email: 'usman.pos@saltnpepper.com.pk',
    role: 'pos_cashier',
    status: 'active',
    branch: 'Gulberg Food Hub',
    phone: '+92 301 7765219',
    lastLogin: '2026-03-10 14:10 PKT',
    createdAt: '2025-06-20',
    permissions: {
      pos: true,
      kds: false,
      inventory: false,
      reports: false,
      staffManagement: false,
      billing: false,
    },
  },
  {
    id: 'USR-PK-401',
    tenantId: 'TEN-5211',
    tenantName: 'Howdy Steak & Burgers Lahore',
    fullName: 'Farhan Zaidi',
    email: 'farhan@howdy.pk',
    role: 'manager',
    status: 'active',
    branch: 'DHA Z-Block Outpost',
    phone: '+92 345 8821903',
    lastLogin: '2026-03-09 22:30 PKT',
    createdAt: '2025-09-08',
    permissions: {
      pos: true,
      kds: true,
      inventory: true,
      reports: true,
      staffManagement: false,
      billing: false,
    },
  },
];

export const INITIAL_DATABASE_SEED_TRANSACTIONS: Transaction[] = [
  {
    id: 'TXN-9910',
    invoiceNumber: 'INV-2026-0381',
    tenantId: 'TEN-8841',
    tenantName: 'The Monal Restaurant Islamabad',
    amount: 350000,
    currency: 'PKR',
    method: '1Link PayPak / Direct Debit',
    status: 'Succeeded',
    date: '2026-03-01',
    billingPeriod: 'Mar 1, 2026 - Mar 31, 2026',
  },
  {
    id: 'TXN-9911',
    invoiceNumber: 'INV-2026-0382',
    tenantId: 'TEN-7102',
    tenantName: 'Kolachi Restaurant Karachi',
    amount: 420000,
    currency: 'PKR',
    method: 'HBL Corporate Wire',
    status: 'Succeeded',
    date: '2026-03-01',
    billingPeriod: 'Mar 1, 2026 - Mar 31, 2026',
  },
  {
    id: 'TXN-9912',
    invoiceNumber: 'INV-2026-0383',
    tenantId: 'TEN-6490',
    tenantName: 'Salt’n Pepper Village Lahore',
    amount: 290000,
    currency: 'PKR',
    method: 'Meezan Bank Raast Fast',
    status: 'Succeeded',
    date: '2026-03-01',
    billingPeriod: 'Mar 1, 2026 - Mar 31, 2026',
  },
  {
    id: 'TXN-9913',
    invoiceNumber: 'INV-2026-0384',
    tenantId: 'TEN-5211',
    tenantName: 'Howdy Steak & Burgers Lahore',
    amount: 145000,
    currency: 'PKR',
    method: 'Visa / MC Corporate',
    status: 'Succeeded',
    date: '2026-03-01',
    billingPeriod: 'Mar 1, 2026 - Mar 31, 2026',
  },
];

export const INITIAL_DATABASE_SEED_PLANS: PlanPricingTier[] = [
  {
    id: 'tier-starter',
    name: 'Starter',
    monthlyPrice: 99,
    annualPrice: 950,
    includedPosTerminals: 2,
    additionalTerminalPrice: 25,
    maxStaffSeats: 5,
    description: 'Perfect for standalone cafes, food trucks, and single-location boutique diners.',
    popular: false,
    features: [
      'Up to 2 POS Terminals',
      '5 Staff Logins',
      'Cloud Kitchen Receipts',
      'Basic Daily Sales PDF Reports',
      'Email Support (48h SLA)',
    ],
  },
  {
    id: 'tier-professional',
    name: 'Professional',
    monthlyPrice: 249,
    annualPrice: 2400,
    includedPosTerminals: 6,
    additionalTerminalPrice: 35,
    maxStaffSeats: 25,
    description: 'Designed for high-throughput multi-floor restaurants and growing casual dining chains.',
    popular: true,
    features: [
      'Up to 6 POS Terminals Included',
      '25 Staff User Accounts',
      'Kitchen Display System (KDS) Routing',
      'Live Table & Order Map',
      'FBR / National Tax POS Ingress',
      'Real-time Multi-tenant Alerts',
      'Priority Discord & Phone Support (4h SLA)',
    ],
  },
  {
    id: 'tier-enterprise',
    name: 'Enterprise',
    monthlyPrice: 599,
    annualPrice: 5800,
    includedPosTerminals: 15,
    additionalTerminalPrice: 30,
    maxStaffSeats: 100,
    description: 'Mission-critical fleet governance for nationwide hospitality groups & luxury franchises.',
    popular: false,
    features: [
      '15+ POS Terminals Included',
      'Unlimited Staff Seats & Roles',
      'Multi-branch Google Maps Geolocation',
      'Custom API Gateways & 1Link Integration',
      'Audit Logging & Security Pin Enforcement',
      'Instant Impersonation & Remote Terminal Reboot',
      'Dedicated Customer Success Architect (15m SLA)',
    ],
  },
];

export const INITIAL_DATABASE_SEED_TELEMETRY: SystemServiceTelemetry[] = [
  {
    id: 'svc-edge-gateway',
    name: 'Multi-Tenant API Gateway (Islamabad Edge)',
    status: 'Operational',
    uptimePercentage: 99.99,
    latencyMs: 14,
    throughput: '14.2k req/s',
    region: 'isb-edge-01 (Islamabad Core)',
  },
  {
    id: 'svc-postgres-cluster',
    name: 'Supabase PostgreSQL Primary',
    status: 'Operational',
    uptimePercentage: 99.98,
    latencyMs: 12,
    throughput: '8.6k qps',
    region: 'ap-south-1 (Mumbai Multi-AZ)',
  },
  {
    id: 'svc-pos-websocket',
    name: 'POS Terminal Live WebSocket Bus (Lahore Node)',
    status: 'Operational',
    uptimePercentage: 99.96,
    latencyMs: 16,
    throughput: '22.8k msgs/s',
    region: 'lhr-mesh-01 (Lahore)',
  },
  {
    id: 'svc-karachi-edge',
    name: 'Coastal Ingress & KDS Dispatch (Karachi)',
    status: 'Operational',
    uptimePercentage: 99.99,
    latencyMs: 11,
    throughput: '18.4k req/s',
    region: 'khi-edge-01 (Karachi)',
  },
  {
    id: 'svc-stripe-webhooks',
    name: '1Link & Digital Pay Webhook Pipeline',
    status: 'Operational',
    uptimePercentage: 100.0,
    latencyMs: 28,
    throughput: '180 events/s',
    region: 'Global Edge Worker',
  },
];

export const INITIAL_DATABASE_SEED_ALERTS: AlertNotification[] = [
  {
    id: 'alert-trial-1',
    title: 'Trial Expiring: Khyber Shinwari Peshawar',
    description: 'Professional Trial period expiring in 8 days. Licensed 5 active POS terminals in Namak Mandi.',
    severity: 'warning',
    timestamp: 'Live Fleet',
    tenantId: 'TEN-4190',
    tenantName: 'Khyber Shinwari Peshawar',
    actionLabel: 'Review Trial',
    actionType: 'view_tenant',
    read: false,
  },
  {
    id: 'alert-ticket-1',
    title: 'Active Ticket: Kolachi Restaurant Karachi',
    description: '1 open support escalation for Do Darya Coastal Waterfront. L2 operational review requested.',
    severity: 'warning',
    timestamp: 'Live Fleet',
    tenantId: 'TEN-7102',
    tenantName: 'Kolachi Restaurant Karachi',
    actionLabel: 'Inspect Outlet',
    actionType: 'view_tenant',
    read: false,
  },
];
